### ISSUE TITLE
Bugs reported on Forums

### ISSUE THREAD

**Issue by ItsTaras** [kito2/mtibia-bounties#5] opened 2018-10-02 14:01 UTC
**Achievements Bugs**
-------------------------------------
_**MOUNTS**_
- [ ] **Out of the Stone Age** = Obtainable by taming Undead Cavebear.
- [ ] **Knock on Wood** = Obtainable by taming a Tin Lizzard (You have to use a Tin Key on a stationay Tin Lizzard.
- [ ] **Scales and Tail** = Obtainable by taming Draptor.
- [ ] **Littel Ball of Wool** = Obtainable by taming Black Sheep.
- [ ] **Golden Sands** = Obtainable by taming Sandstone Scorpion.
- [ ] **Loyal Lad** = Obtainable by taming Donkey.
- [ ] **Friend of Elves** = Obtainable by taming Enraged White Deer.
- [ ] **Stuntman** = Obtainable by taming Uniwheel (You have to use a Golden Can of Oil on a stationary Uniwheel.
- [ ] **Lucky Horseshoe** = Obtainable by taming Wild Horse.
- [ ] **Magnetised** = Obtainable by taming Ironblight.
- [ ] **Dragon Mimicry** = Obtainable by taming Dragonling.
- [ ] **Mind the Dog!** = Obtainable by taming Modified Gnarlhound.
- [ ] **Personal Nightmare** = Obtainable by taming Shock Head.
- [ ] **Lion King** = Obtainable by taming Noble Lion.

_**OUTFITS**_
- [ ] **Beak Doctor** = Obtainable by getting both addons of Afflicted Outfits.
- [ ] **Swift Death** = Obtainable by getting both addons of Assassin Outfits.
- [ ] **Brutal Politeness** = Obtainable by getting both addons of Barbarian Outfits.
- [ ] **Exalted Battle Mage** = Probably obtainable by getting both addons of Battle Mage Outfits.
> Needed more information. It's related with The Secret Library Quest.
- [ ] **Life on the Streets** = Obtainable by getting both addons of Beggar Outfits.
- [ ] **Skull and Bones** = Obtainable by getting both addons of Brotherhood Outfits.
- [ ] **Cave Completionist** = Obtainable by getting both addons of Cave Explorer Outfits.
- [ ] **Exemplary Citizen** = Obtainable by getting both addons of Citizen Outfits.
- [ ] **Crystal Clear** = Obtainable by getting both addons of Crystal Warlord Outfits.
- [ ] **Spolium Profundis** = Obtainable by getting both addons of Deepling Outfits.
- [ ] **Demonbane** = Obtainable by getting both addons of Demon Hunter Outfits.
- [ ] **True Dedication** = Obtainable by getting both addons of Demon Outfits.
- [ ] **Dream Warden** = Obtainable by getting both addons of Dream Warden Outfits.
- [ ] **Dream Warrior** = Obtainable by getting both addons of Dream Warrior Outfits.
- [ ] **Of Wolves and Bears** = Obtainable by getting both addons of Druid Outfits.
- [ ] **Mystic Fabric Magic** = Obtainable by getting both addons of Elementalist Outfits.
- [ ] **Reason to Ceebrate** = Obtainable by getting both addons of Festive Outfits.
- [ ] **Glooth Engineer** = Obtainable by getting both addons of Glooth Engineer Outfits.
- [ ] **Hunting with Style** = Obtainable by getting both addons of Hunter Outfits.
- [ ] **Bane of the Hive** = Obtainable by getting both addons of Insectoid Outfits.
- [ ] **Fool at Heart** = Obtainable by getting both addons of Jester Outfits.
- [ ] **In Shining Armor** = Obtainable by getting both addons of Knight Outfits.
- [ ] **Alumni** = Obtainable by getting both addons of Mage Outfits.
- [ ] **Cobbled and Patched** = Obtainable by getting both addons of Makeshift Warrior Outfits.
- [ ] **Nightmare Walker** = Obtainable by getting both addons of Nightmare Outfits.
- [x] **Aristocrat** = Obtainable by getting both addons of Nobleman Outfits.
- [ ] **Out in the Snowstorm** = Obtainable by getting both addons of Norseman Outfits.
- [ ] **One Thousand and One** = Obtainable by getting both addons of Oriental Outfits.
- [ ] **Swashbuckler** = Obtainable by getting both addons of Pirate Outfits.
- [ ] **Rift Warrior** =  Obtainable by getting both addons of Rift Warrior Outfits.
- [ ] **Way of the Shaman** =  Obtainable by getting both addons of Shaman Outfits.
- [ ] **Funghistastic** = Obtainable by getting both addons of Soil Guardian Outfits.
- [ ] **Ritualist** = Obtainable by getting both addons of Summoner Outfits.
- [ ] **Master of War** = Obtainable by getting both addons of Warmaster Outfits.
- [ ] **Wild Warrior** = Obtainable by getting both addons of Warrior Outfits.
- [ ] **Peazzekeeper** = Obtainable by getting both addons of Wayfarer Outfits.
- [ ] **Warlock** = Obtainable by getting both addons of Wizard Outfits.

_**OTHERS**_
- [ ] **Cookie Monster** = Obtainable by baking 20 trays of cookies (240 cookies in total): It could be bugged but it isn't tested yet because the following item is reported as a bug: Baking Tray.
- [ ] **Elite Hunter** = Obtainable by ascending to Elite Hunter in the Paw and Fur Society.
- [ ] **The Cake's the Truth** = Obtainable by baking 30 cakes.
- [ ] **Grand Master Oberon** = Looking for information about it. Maybe LIBRARY LIBERATOR.

**High priority Bugs**
-------------------------------------
- [ ] Exercise Rod. (Hakugen)
> NPCs sell this item with 100 charges instead of 500.
`Only happens when buying with containers.`
- [ ] Warzone. (Maravilinda)
> He went to do the task, talked with NPC and did it but he couldn't report.
- [ ] Doesn't count inq gold in Blowing Horns Task in Roshamuul (Unknown Ek)
- [ ] EKs are hitting so much when they use elemental damage.
- [ ] The Postman Quest -Mission 7- is bugged. When you have to report with Lokur.

**Low priority bugs**
-------------------------------------
- [ ] Bug in students dorm teleport - The Gravedigger of Drefia Quest (Sor Doug)
- [ ] Re-do Brokul & Neutral Deepling (XML: damages, HP, resistences) then, test configuration for quest.
- [ ] Gravedigger of Drefia: [Forum link](https://mtibia.online/forum.php?forum=Report%20Bugs&cat=3&thread=1446) >>>>> https://github.com/kito2/mtibia-bounties/issues/16
- [ ] War Against the Hive: 
> Questlog doesn't count the task you have to do.
> Insectoid antenna doesn't respawn to continue the task.
> Blob bomb doesn't work in its task.
> Information:
> When you say (HI - MISSION - BLIND - DIGESTION - ACID - DISABLE - YES) the NPC only answer Blind's mission and Disable's mission.
>> Digestion mission isn't working because NPC doesn't give you the red egg who is used to catch larvas.
>> That's the answer when you ask for Digestion mission and NPC doesn't give you the item:
>> 14:12 Orockle: Fight! You can always help me out on the War Against the Hive to claim insectoid outfit with their related first addon and second addon.
>> 14:12 Sephiroth [260]: mission
>> 14:12 Orockle: You could try to blind the hive, you might disrupt its digestion, you could gather acid or you can disable the swarm pores. ...
>> 14:12 Orockle: Due to our recent success, the hives' defences are broken and it is also possible to kill the guards or to break the control crystals ...
>> 14:12 Orockle: You can always quit a mission of course.
>> 14:12 Sephiroth [260]: digestion
>> 14:12 Orockle: You should disrupt at least 7 floor blob before reporting...
>> Acid mission isn't working because NPC doesn't give you the flask.
- [ ] Orcs Raid in Thais didn't start. (Silker)
>"Some Orcs are assembling north of Thais." --> [https://tibia.fandom.com/wiki/Mapper?coords=126.108,125.24,7,2,1,1](url)

**Comment by ItsTaras** [comment] 2018-10-02 14:42
----------------------------------------------
**Revisión para el futuro de monstruos o bosses.**
- [ ]   **Glooth Fairy**
Han reportado de que el boss se cura demasiadas veces.
 `-   `
----------------------------------------------

**Comment by ItsTaras** [comment] 2018-10-02 15:21
** BUGs del cliente **
´Buenas tardes,
no se si se trata de bug, pero al momento de atacar monster con "chase" y obviamente te mueves se pierde, pero que pasa si yo vuelvo a colocar "chase opponent" atacando no lo sigue, tienes que volver a targetearlo para que lo siga, tengo entendido que si uno esta atacando un monster con "stand" y aprieta "chase"debiera seguirlo sin necesidad de tener que volver a targetear el mosnter, muchas gracias.´

**Comment by kito2** [comment] 2018-10-05 15:29
**Hechos**

**Comment by kito2** [comment] 2018-10-11 19:03
**No posible de corregir:**
--------------------------------------------------
- [ ]  Cuando los monstruos lanzan fields.
 `Ejemplo dragon lord lanza fire pega mas rápido de lo que debería `
 **BUG experimentado tambien una vez en asuras, pero no consigo reproducirlo de nuevo, asi que no se como se bugea exactamente, falta testearlo**
> Se ha presenciado en otras situaciones, escapa de mis conocimientos para corregir.
- [ ] Las municiones en slot de arrow tienen diferente formula de calculo de daño que municiones que van en la main-hand.

**Agendados (para otros programadores) pero no resueltos**
--------------------------------------------------
- [ ] Los containers estando en el depot, no se pueden meter items adentro. Lo que sucede es que el item se mueve adentro del depot y desplaza todos los items un SQM.
> No es posible stackear items en containers con paginacion, ni tampoco mover items dentro de las backpacks, video explciativo: https://youtu.be/RV5hLRV9bkY
> Comentario: Aun al mover items al depot box, que tiene container en el SQM, y el container tiene espacio para mover el item, lo mueve al depot box, en vez del container. Importante notar que si el container no tiene espacio, entonces el mensaje de "Not enough space on container" deberia aparecer.

**Comment by kito2** [comment] 2018-10-11 19:04
**Agendados (para otros programadores) pero no resueltos**
--------------------------------------------------
- [ ] Los containers estando en el depot, no se pueden meter items adentro. Lo que sucede es que el item se mueve adentro del depot y desplaza todos los items un SQM.
> No es posible stackear items en containers con paginacion, ni tampoco mover items dentro de las backpacks, video explciativo: https://youtu.be/RV5hLRV9bkY
> Comentario: Aun al mover items al depot box, que tiene container en el SQM, y el container tiene espacio para mover el item, lo mueve al depot box, en vez del container. Importante notar que si el container no tiene espacio, entonces el mensaje de "Not enough space on container" deberia aparecer. 
- [ ] Hubo varios reportes de que algunos monstruos en roshamuul como guzzlemaw, frazzlemaw o silencer también arojan vials y pots al piso.
- [ ] Al agregar la jewelled backpack al auto loot, y lootearla de un cuerpo, hace que el cliente de mtibia se cierre automáticamente.

**Comment by kito2** [comment] 2018-11-09 16:01
**Won't fix**
---------------------------------------------
- [x] El Soul sigue bajando en los training monks a pesar de tener full stamina (42:00). 
> No se corregira ya que se eliminaran los trainers online.

**Comment by kito2** [comment] 2018-12-11 19:53
**Won't fix**
-----------------------------------------------
- [x] Stamina (Hakugen)
> He logged in and had 40:42, but when he logged out, after hunting, his stamina had been increased to 42:00.
_Not enought data._
- [x] Regeneration problem? (Kadeus) 
> [https://mtibia.online/forum.php?forum=Report%20Bugs&cat=3&thread=1640](url)
_Not enought data._
- [x] Wild Horse. (Dravekan)
> The place where it should respawn is wrong. It should respawn there --> (32470, 32260, 7)
> Attending to Tibia Wiki, the respawn is from 1 to 3 Wild Horses, but the player affirms that it respawning one by one.
> He also said that the taming ratio is lower than RL.
_The idea is make it harder, compared to RL, since it's a really easy mount and it's not 100% as RL yet._

**Closed** 2018-12-25 05:34 UTC
Labels: bug
